language: java
sudo: false
install: true
addons:
   sonarcloud:
      organization: "302160a7986b1a33c2a3c66b7514dcf2e06900c8"
      token:
         secure: "ZvWBRqY4cWAVrVEPyjLZ"
jdk:
   - oraclejdk8
script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
   directories:
      - '$HOME/.m2/repository'
      - '$HOME/.sonar/cache'
